name: Deploy to Netlify

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: '3.1'
    - run: dotnet run -- deploy
      env:
        NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        NETLIFY_WEBSITE_ID: ${{ secrets.NETLIFY_WEBSITE_ID }}
